analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"

include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    sort_constructors_first: true
